name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    # Configure Docker with Credentials
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build & Publish
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_APPLICATION: ${{ secrets.GCP_APPLICATION }}
      run: |
        echo "GCP_PROJECT_ID=${GCP_PROJECT_ID}""
        gcloud config set project ${GCP_PROJECT_ID}
        gcloud builds submit --tag gcr.io/${GCP_PROJECT_ID}/${GCP_APPLICATION}
        gcloud config set run/region europe-west4
      
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_APPLICATION: ${{ secrets.GCP_APPLICATION }}
      run: |
        gcloud run deploy ${GCP_APPLICATION} --image gcr.io/${GCP_PROJECT_ID}/${GCP_APPLICATION} \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M